### PR TITLE
[EPAUTH-75] Display an the incompatible browser configuration if https is not enabled on Chrome

### PR DESCRIPTION
**Pull request by san983**
voxbone_widget_generator_v0_2_2

### CODE REVIEW

**Comment by tsearle** [comment]
Do not delete widget-0.2.js and widget-0.1.js  The widget generator officially hosts these files ad removing them will break production widgets generated by previous versions of the widget generator.

**Comment by san983** [comment]
Hi @tsearle, I'll put back those deleted files. I think I get confused since when we have deployed to production last week we were only using `0.3`. But now I realised it was already on prod before that. My bad

**Comment by san983** [comment]
@tsearle I don't think the `isSupported()` is the best option, since that is intended for non WebRTC compatible browsers like Safari or IE 9 for example.
The idea here is to show the client who is implementing the widget in his site, that it should be on HTTPS to work with Chrome. Thoughts @chadwallacehart ?

**Comment by chadwallacehart** [comment]
There are 2 scenarios:
1. Voxbone customer is using the widget generator portal to generate some code. In this case they could be using the widget generator portal to make code, but might not have a WebRTC browser
2. A Voxbone customer website visitor accesses a webpage via HTTP. If the customer gets to this page then the Voxbone customer who is hosting the widget probably made a mistake. If that should happen then the end-customer should see the incompatible browser configuration - perhaps with a console.log message

We can split this into 2 issues if needed.

**Comment by tsearle** [comment]
@chadwallacehart

Case 1 is already taken care of, the value of supported is forced in the preview mode

so the only question is that in Case 2, should the customer see the error after making a call attempt (as currently implemented in this pull request) or should it be reported right away.  My impression is you are in favor of the latter.

**Comment by chadwallacehart** [comment]
I don't think case 1 is taken care of, but that probably should be in another issue.

On case 2 - I agree the customer should never have an opportunity to click on a button that won't work. Let's discuss on the stand-up in a few.

**Pull request closed without merging**
